{
 "title": "Assignment DashBoard",
 "time": { "from": "2024-05-04T10:33:24.372Z", "to": "2024-05-04T12:15:48.373Z" },
 "panels": [
  {
   "title": "Process Ram Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cpu Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Processing Time Per Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "total_time_ms", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Process Time Per Pixel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 8 },
   "targets": [
    { "expr": "processing_time_per_char_us", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(client_ip) (app_requests_total{endpoint=\"/predict\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}